services:
  rss-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    image: rss_crawler_v8:latest
    container_name: rss_crawler_v8
    restart: unless-stopped

    environment:
      - TZ=Asia/Ho_Chi_Minh

    volumes:
      - ./multi_source_seen.bloom:/app/multi_source_seen.bloom
